THEORY QUESTIONS


1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it 
enhance Python's capabilities for numerical operations?

Purpose: NumPy (Numerical Python) is a powerful library in Python that provides support for arrays, matrices, and a wide range of mathematical functions to perform operations on these data structures efficiently.

Advantages:

Performance: NumPy is implemented in C, allowing for efficient execution of operations. It is significantly faster than pure Python code for numerical calculations.
Memory Efficiency: NumPy arrays use contiguous blocks of memory, which reduces overhead and increases performance, especially with large datasets.
Convenience: It provides a wide variety of built-in mathematical functions, making it easy to perform complex calculations with less code.
Multidimensional Arrays: NumPy allows for the creation and manipulation of n-dimensional arrays, making it suitable for a wide range of applications in data analysis, machine learning, and scientific computing.
Interoperability: It integrates well with other libraries, such as SciPy, Pandas, and Matplotlib, enhancing Python’s capabilities for data analysis and visualization.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the 
other?

np.mean(): Computes the arithmetic mean along a specified axis. It treats all elements equally.
np.average(): Also computes the average, but it allows for weights to be specified. This means you can give different weights to different elements, affecting the result.
Usage:

Use np.mean() when you need the standard mean of the array.
Use np.average() when you need to account for weights in your average calculation.

In [17]:
#3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

arr1D = np.array([1, 2, 3, 4, 5])
reversed_1D = arr1D[::-1]
print(reversed_1D)  


[5 4 3 2 1]


In [18]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
arr = np.array([1, 2, 3.5])
print(arr.dtype)  

#Importance:Memory Management: Different data types consume different amounts of memory. Choosing an appropriate data type can save memory.
#Performance: Operations on certain data types (like integers and floats) can be faster compared to others (like objects or strings).

float64


5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ndarray: The core data structure in NumPy is the n-dimensional array (ndarray), which can hold multiple dimensions of data.

Key Features:

Homogeneous: All elements in an ndarray must be of the same data type.
Multidimensional: Can be one-dimensional, two-dimensional (like matrices), or higher-dimensional.
Efficient: Stores data in contiguous memory locations for performance.
Differences from Python Lists:

Type Homogeneity: Ndarrays require all elements to be of the same type, while lists can contain mixed types.
Performance: Ndarrays provide better performance for numerical operations due to optimized storage and operations.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Speed: NumPy operations are implemented in C and optimized for performance, making them faster than Python lists for large-scale numerical computations.
Memory Usage: NumPy arrays have lower memory overhead due to their contiguous memory allocation, allowing for better utilization of system memory.
Vectorization: NumPy can perform operations on entire arrays without the need for explicit loops, leveraging SIMD (Single Instruction, Multiple Data) operations.

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and 
output.

np.vstack():
Purpose: Stacks arrays in sequence vertically (row-wise).
Input: Takes a tuple of arrays as input, all of which should have the same number of columns.
np.hstack():
Purpose: Stacks arrays in sequence horizontally (column-wise).
Input: Takes a tuple of arrays as input, all of which should have the same number of rows.

In [19]:

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

vstack_result = np.vstack((a, b))  
print("Vertical Stack:\n", vstack_result)

hstack_result = np.hstack((a, b.T))  
print("\nHorizontal Stack:\n", hstack_result)


Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]]

Horizontal Stack:
 [[1 2 5]
 [3 4 6]]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various 
array dimensions.
np.fliplr():

Purpose: Flips an array from left to right (horizontal flip).
Effect: Each row of the array is reversed.
np.flipud():

Purpose: Flips an array from up to down (vertical flip).
Effect: The order of the rows is reversed.

In [20]:
arr2D = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("Original Array:\n", arr2D)

flipped_lr = np.fliplr(arr2D)
print("\nFlipped Left to Right:\n", flipped_lr)

flipped_ud = np.flipud(arr2D)
print("\nFlipped Up to Down:\n", flipped_ud)


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped Left to Right:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]

Flipped Up to Down:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

np.array_split() is used to split an array into multiple sub-arrays. It can handle uneven splits by allowing some sub-arrays to contain one more element than others.

Key Features:
It takes the original array and the number of splits desired as input.
If the number of elements in the array is not divisible by the number of splits, it distributes the remaining elements among the first few sub-arrays.

In [21]:
arr = np.array([1, 2, 3, 4, 5])

split_result = np.array_split(arr, 3)
print("Array Split Result:\n", split_result)


Array Split Result:
 [array([1, 2]), array([3, 4]), array([5])]


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array 
operations?

Vectorization:
Refers to the process of converting operations that would typically require explicit loops into a form that allows NumPy to process them in bulk.
It takes advantage of NumPy’s optimized C and Fortran libraries, enabling faster computations.

In [22]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = a + b
print("Vectorized Addition Result:", result)


Vectorized Addition Result: [5 7 9]


CODING QUESTIONS

In [2]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np
array = np.random.randint(1, 101, size=(3, 3))
transposed_array = np.transpose(array)
array, transposed_array


(array([[65, 38, 68],
        [14, 18, 89],
        [ 2, 47, 72]]),
 array([[65, 14,  2],
        [38, 18, 47],
        [68, 89, 72]]))

In [5]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

array_1d = np.random.randint(1,10,10)
array_2x5 = array_1d.reshape(2, 5)
array_5x2 = array_1d.reshape(5, 2)
array_1d, array_2x5, array_5x2


(array([6, 2, 1, 1, 8, 4, 5, 2, 9, 5]),
 array([[6, 2, 1, 1, 8],
        [4, 5, 2, 9, 5]]),
 array([[6, 2],
        [1, 1],
        [8, 4],
        [5, 2],
        [9, 5]]))

In [6]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

array_4x4 = np.random.rand(4, 4)
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("4x4 Array:\n", array_4x4)
print("\n6x6 Array with Zero Border:\n", array_6x6)


4x4 Array:
 [[0.52741606 0.41734909 0.59988679 0.00859935]
 [0.5012297  0.6778837  0.73559725 0.34787305]
 [0.25527107 0.5254243  0.32510828 0.18207245]
 [0.84972266 0.71793245 0.64532989 0.74836363]]

6x6 Array with Zero Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.52741606 0.41734909 0.59988679 0.00859935 0.        ]
 [0.         0.5012297  0.6778837  0.73559725 0.34787305 0.        ]
 [0.         0.25527107 0.5254243  0.32510828 0.18207245 0.        ]
 [0.         0.84972266 0.71793245 0.64532989 0.74836363 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [7]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

print(array)


[10 15 20 25 30 35 40 45 50 55 60]


In [8]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

array = np.array(['python', 'numpy', 'pandas'])
upper_case = np.char.upper(array)
lower_case = np.char.lower(array)
title_case = np.char.title(array)

print("Original Array:", array)
print("Uppercase:", upper_case)
print("Lowercase:", lower_case)
print("Title Case:", title_case)


Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']


In [9]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

words_array = np.array(['hello', 'world', 'numpy', 'array'])
spaced_array = np.char.join(' ', words_array)

print("Original Array:", words_array)
print("Array with Spaces:", spaced_array)


Original Array: ['hello' 'world' 'numpy' 'array']
Array with Spaces: ['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


In [10]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("\nElement-wise Addition:\n", addition)
print("\nElement-wise Subtraction:\n", subtraction)
print("\nElement-wise Multiplication:\n", multiplication)
print("\nElement-wise Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]

Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [11]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

identity_matrix = np.eye(5)
diagonal_elements = np.diag(identity_matrix)

print("5x5 Identity Matrix:\n", identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]


In [12]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

random_integers = np.random.randint(0, 1001, size=100)

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True
prime_numbers = [num for num in random_integers if is_prime(num)]
print("Random Integers Array:", random_integers)
print("\nPrime Numbers in the Array:", prime_numbers)


Random Integers Array: [878 853 816 876  31 687 775 523 134 759 257 967  45 884 856 167  34 273
  88 616 987  51 199 494 208 774 696   6 891 753  39  65 232 832 532 117
  85 531 719 587  49 902 652  29 609  57 366 491 392 858 592 328 911 509
 623 241 559 357 542 591 829 311 280 545 626 523 531 346 457 474  34 468
 267 361 720 917 386 207 672 175 179 714 105 337 432 551 157 661 960 994
 991 424 320 397 927 701 838 655 798 425]

Prime Numbers in the Array: [853, 31, 523, 257, 967, 167, 199, 719, 587, 29, 491, 911, 509, 241, 829, 311, 523, 457, 179, 337, 157, 661, 991, 397, 701]


In [16]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

daily_temperatures = np.random.randint(15, 31, size=28)

weekly_temperatures = daily_temperatures.reshape(4, 7)
weekly_averages = np.mean(weekly_temperatures, axis=1)

print("Daily Temperatures for the Month:", daily_temperatures)
print("\nWeekly Averages:", weekly_averages)


Daily Temperatures for the Month: [18 15 17 29 17 23 30 24 27 19 17 24 30 19 22 18 20 22 15 17 18 20 23 17
 28 29 25 27]

Weekly Averages: [21.28571429 22.85714286 18.85714286 24.14285714]
